Fixes from mmcint/synthoseis-testing + relative paths for directories
studio-x-llc/synthoseis pull request #1
Opened 2023-07-26 00:16 UTC by csamuel

- Incorporate @mmcint fixes from https://github.com/mmcint/synthoseis-testing
- Update `environment.yml` to use python 3.9
- Ignore `.DS_Store` files
- Use relative paths to reference the config and project/work directories
- Add `output/` directory for generate model/work/temp files and ignore everything inside it

2023-07-26 00:18 UTC, csamuel commented
The diff isn't readable, so here's the change to the notebook:

![CleanShot 2023-07-25 at 19 17 22@2x](https://github.com/studio-x-llc/synthoseis/assets/15816/b1f53faf-6e36-4801-a378-89b81452e399)

2023-07-27 17:22 UTC, mmcint requested changes, later dismissed
there are a few changes, but for the most part it looks good

2023-07-27 17:22 UTC, mmcint commented on config/example.json
> -  "closure_types": ["simple", "faulted", "onlap"],
let's add 'faulted' and 'onlap' back in. i was just testing different cases

2023-07-27 17:22 UTC, mmcint commented on datagenerator/Closures.py
> -        # return top_lith_indices
i was attempting to get the horizon tops by returning top lithology indices. we can ignore this change

2023-07-27 17:22 UTC, mmcint commented on main.py
here i was just trying to debug and understand where the errors were occuring. we can leave in or take out. up to you @csamuel

2023-07-27 17:31 UTC, csamuel commented on main.py
Got it, will remove

2023-07-27 17:43 UTC, csamuel commented
@mmcint Think I addressed all your feedback if you want to take another look

2023-07-27 17:43 UTC, chadac commented on config/example.json
> +  "project_folder": "./output/test4",
Is this a test artifact?

2023-07-27 17:43 UTC, chadac commented on environment.yml
> +  - python=3.9
Betting this would work for 3.10 as well.

2023-07-27 17:52 UTC, mmcint commented on config/example.json
> +  "project_folder": "./output/test4",
yes. but the `project` category is hard coded as `example1` in another script, so we should keep it in there

2023-07-27 17:54 UTC, mmcint commented on environment.yml
> +  - python=3.9
lets do it. i set this up in python 3.9 bc it was the earliest version i could get

2023-07-27 17:57 UTC, mmcint approved these changes
looks good. feel free to convert to python 3.10 @chadac

2023-07-27 18:05 UTC, csamuel commented on config/example.json
> +  "project_folder": "./output/test4",
That actually reminds, me I meant ask what the story was herechecking for this specific `example1` project? https://github.com/studio-x-llc/synthoseis/blob/master/rockphysics/RockPropertyModels.py#L144-L149

2023-07-27 18:28 UTC, chadac approved these changes

2023-07-27 18:40 UTC, mmcint commented on config/example.json
> +  "project_folder": "./output/test4",
i'm not sure i understand the if statement part, but essentially it's loading in the rock properties model (rock and fluid velocity properties) that is used to take the geomodel and convert to seismic

2023-07-27 18:46 UTC, merged